export const CALCULATION_INPUT_ACTION = 'CALCULATION_INPUT_ACTION';
export const NUMBER_INPUT = 'NUMBER_INPUT';
export const OPERATOR_INPUT = 'OPERATOR_INPUT';
export const OPEN_BRACKET_INPUT = 'OPEN_BRACKET_INPUT';
export const CLOSING_BRACKET_INPUT = 'CLOSING_BRACKET_INPUT';

export const CLEAR_ENTRY = 'CLEAR_ENTRY';
export const ALL_CLEAR = 'ALL_CLEAR';

export const CALCULATE = 'CALCULATE';
